### ISSUE TITLE
Build tags on docker hub

### ISSUE THREAD

**Issue by janschultecom** [castlemock/docker#1]
Thanks for this cool project. Would it be possible to create docker builds on docker hub with tags corresponding to the source tags?

**Comment by karldahlgren** [comment]
Hi @janschultecom.
Thank you for you comment!
Just to clarify: You want to have a Docker build for each individual tag? Today, we only use tags to identify different versions; so that would mean that we have Docker builds for each version. Have I understood you correct?

I could do some investigation on this during the weekend and come back to you after that. How does that sound to you?

Thanks!
Best regards,
Karl Dahlgren

**Comment by janschultecom** [comment]
Yes exactly. One docker build for each individual tag.
Right now one can only depend on the docker 'latest' image or build the image self from source. So relying on the latest is not a good option, because it might break things as soon as you do some breaking changes to the code and rebuild the latest image.

**Comment by karldahlgren** [comment]
Closing this issue since it has been resolved. All the builds can now been found on the following page:  https://hub.docker.com/r/castlemock/castlemock/builds/
